UnitTestBot/usvm

- usvm-jvm-instrumentation/src/main/kotlin/org/usvm/instrumentation/agent/Agent.kt
- usvm-jvm-instrumentation/src/main/kotlin/org/usvm/instrumentation/executor/InstrumentationProcessPaths.kt
- usvm-jvm-instrumentation/src/main/kotlin/org/usvm/instrumentation/executor/InstrumentationProcessRunner.kt
- usvm-jvm-instrumentation/src/main/kotlin/org/usvm/instrumentation/executor/UTestConcreteExecutor.kt
- usvm-jvm-instrumentation/src/main/kotlin/org/usvm/instrumentation/util/Constants.kt
- usvm-jvm-instrumentation/src/test/kotlin/org/usvm/instrumentation/executor/UTestConcreteExecutorTest.kt
- usvm-jvm/src/main/kotlin/org/usvm/types/ClassScorer.kt
- usvm-jvm/src/main/kotlin/org/usvm/util/JcApproximationUtils.kt
- usvm-jvm/src/test/kotlin/org/usvm/util/UTestRunner.kt
This PR allows changing of how paths to jars and Java are retrieved. Previously path were always retrieved by reading environment variables, but in UtBot we need to dynamically change these paths without starting a new process.
> Allow configuring how jar paths are retrieved

- usvm-jvm-instrumentation/src/collectors/java/org/usvm/instrumentation/collector/trace/TraceCollector.java
Java interprets `(int) x % capacity` as `((int) x) % capacity`. Therefore, whenever 33-rd bit of `x` is `1`, then `((int) x)` is negative and hence `(int) x % capacity` is also negative and can't be used as an array index.
In the current implementation 5-th byte of `key` stores the lower byte of the `methodId: Long`, meaning that for classes with over 128 methods 33-rd bit of `key` can be `1`, which ultimately causes `jcInstructionCovered()` to fail with `IndexOutOfBoundsException`.
> Fix `int` overflow in `TraceCollector.hash()`

- usvm-jvm-instrumentation/src/main/kotlin/org/usvm/instrumentation/util/Jar.kt
- usvm-jvm-instrumentation/src/samples/java/example/AnnotatedMethodClass.java
- usvm-jvm-instrumentation/src/samples/java/example/MyAnnotation.java
- usvm-jvm-instrumentation/src/test/kotlin/org/usvm/instrumentation/executor/ConcreteExecutorTests.kt
- usvm-jvm-instrumentation/src/test/kotlin/org/usvm/instrumentation/util/UTestCreator.kt
Bytecode transformation looses method annotation (field annotations and parameter annotations may also get lost after bytecode transformation, but I have not checked that).
Added test fails with the following output:
```
Debug | ByteBufferAsyncProcessor  | 1:Test worker @coroutine#147 | PAUSE ('Socket not connected') :: {id = usvm-executor-socket/Sender, state = 'Initialized'} 
Debug | Server                    | 99:usvm-executor-socket | usvm-executor-socket: listening /127.0.0.1:44447 
Debug | Server                    | 99:usvm-executor-socket | usvm-executor-socket : connected 
Debug | ByteBufferAsyncProcessor  | 99:usvm-executor-socket | RESUME :: {id = usvm-executor-socket/Sender, state = 'AsyncProcessing'} 
Expected :1
Actual   :0
<Click to see difference> …
```
> Fix annotated method instrumentation

- usvm-jvm-instrumentation/src/main/kotlin/org/usvm/instrumentation/instrumentation/JcInstructionTracer.kt
- usvm-jvm-instrumentation/src/samples/java/example/ClassWithStaticField.java
- usvm-jvm-instrumentation/src/samples/java/example/ParentStaticFieldUser.java
- usvm-jvm-instrumentation/src/test/kotlin/org/usvm/instrumentation/executor/ConcreteExecutorTests.kt
- usvm-jvm-instrumentation/src/test/kotlin/org/usvm/instrumentation/util/UTestCreator.kt
In JVM bytecode (and in `JcRawInst`) static fields can be accessed via child class. That causes bytecode transformation of the added `example.ParentStaticFieldUser` class to fail with the following exception, this PR fixes that issue.
```
java.lang.IllegalStateException: Field not found
at org.usvm.instrumentation.instrumentation.JcInstructionTracer.encodeStaticFieldAccess(JcInstructionTracer.kt:133)
at org.usvm.instrumentation.instrumentation.JcRuntimeTraceInstrumenter.instrumentMethod(JcRuntimeTraceInstrumenter.kt:66)
at org.usvm.instrumentation.instrumentation.JcRuntimeTraceInstrumenter.instrumentClass(JcRuntimeTraceInstrumenter.kt:94)
at org.usvm.instrumentation.agent.ClassTransformer.transform(ClassTransformer.kt:42)
at java.instrument/java.lang.instrument.ClassFileTransformer.transfo …
```
> Fix parent static field instrumentation

- usvm-jvm-instrumentation/src/samples/java/example/AnnotatedMethodClass.java
- usvm-jvm-instrumentation/src/samples/java/example/AnnotationsEx.java
- usvm-jvm-instrumentation/src/samples/java/example/MyAnnotation.java
- usvm-jvm-instrumentation/src/test/kotlin/org/usvm/instrumentation/executor/ConcreteExecutorTests.kt
- usvm-jvm-instrumentation/src/test/kotlin/org/usvm/instrumentation/util/UTestCreator.kt
Instrumenting annotation classes causes default values to get lost. In the added test `UTestExecutionExceptionResult` is returned with the following exception message:
```
example.MyAnnotation missing element x
```
Here are the logs:
```
Debug | ByteBufferAsyncProcessor  | 1:Test worker @coroutine#147 | PAUSE ('Socket not connected') :: {id = usvm-executor-socket/Sender, state = 'Initialized'} 
Debug | Server                    | 99:usvm-executor-socket | usvm-executor-socket: listening /127.0.0.1:33153 
Debug | Server                    | 99:usvm-executor-socket | usvm-executor-socket : connected 
Debug | ByteBufferAsyncProcessor  | 99:usvm-executor-socket | RESUME :: {id = usvm-executor-socket/Sender, state = 'AsyncProcessing'} 
org.opentest4j.AssertionFailedError: Expected value to be …
```
> Add test for annotation default value instrumentation

- buildSrc/src/main/kotlin/DetektConfiguration.kt
This PR fixes the execution of tests on `gradle build` execution.
Previous code was retaining only TASKS (`it is TaskProvider`), excluding the "detekt" task. However, since "test tasks" are not exactly `TaskProvider`, but "TestSuite", all tests were also "unintentionally" filtered out.
You can debug it yourself by the following code in `DetektConfiguration.kt`:
```
tasks.named("check").configure {
println("task = $this")
println("dependsOn: ${dependsOn.toList()}")
for (dep in dependsOn) {
println("- ${dep::class.java}")
}
println("filtered: ${dependsOn.filter { it is TaskProvider<*> && it.name != "detekt" }}")
setDependsOn(dependsOn.filterNot { it is TaskProvider<*> && it.name == "detekt" })
}
```
If the filtering of tests was actually intentional, it should be documented in comments to …
> Enable tests by fixing the filtering of "check" task dependencies

- usvm-core/build.gradle.kts
This PR changes the dependency on "kotlinx-collections-immutable" from `implementation` to `api`.
`persistentHashMapOf()` is being used as default argument in constructors in many PUBLIC classes, making it a part of a public API of USVM. In order to use such public constructors from outside, the user have to also depend on "kotlinx-collections-immutable" by himself. It is better to fix it "on our side" by marking the dependency "api".
> Fix API-dependency on kotlinx-collections

- usvm-jvm/src/test/kotlin/org/usvm/samples/approximations/ApproximationsTest.kt
- usvm-jvm/src/test/kotlin/org/usvm/samples/approximations/SymbolicCollectionModelTest.kt
Disable failing tests until the next version of approximations
> Disable some tests to fix CI pipeline

- usvm-jvm/src/main/kotlin/org/usvm/machine/interpreter/JcExprResolver.kt
- usvm-jvm/src/main/kotlin/org/usvm/machine/interpreter/JcMultiDimArrayAllocationTransformer.kt
- usvm-jvm/src/samples/java/org/usvm/samples/arrays/MultiDimensional.java
- usvm-jvm/src/test/kotlin/org/usvm/samples/JacoDBContainer.kt
- usvm-jvm/src/test/kotlin/org/usvm/samples/arrays/TestMultiDimensional.kt
Rewrite multi-dim array allocation with loops. Fixes #212
> usvm-jvm: Support arrays with multiple dimensions

- usvm-jvm-dataflow/src/main/kotlin/org/usvm/dataflow/jvm/flow/AbstractFlowAnalysis.kt
- usvm-jvm-dataflow/src/main/kotlin/org/usvm/dataflow/jvm/flow/BackwardFlowAnalysis.kt
- usvm-jvm-dataflow/src/main/kotlin/org/usvm/dataflow/jvm/flow/FlowAnalysis.kt
- usvm-jvm-dataflow/src/main/kotlin/org/usvm/dataflow/jvm/flow/FlowAnalysisImpl.kt
- usvm-jvm-dataflow/src/main/kotlin/org/usvm/dataflow/jvm/flow/ForwardFlowAnalysis.kt
- usvm-jvm-dataflow/src/main/kotlin/org/usvm/dataflow/jvm/flow/NullAssumptionAnalysis.kt
- usvm-jvm-dataflow/src/main/kotlin/org/usvm/dataflow/jvm/flow/ReachingDefinitionsAnalysis.kt
- usvm-jvm-dataflow/src/samples/java/NullAssumptionAnalysisExample.java
- usvm-jvm-dataflow/src/test/kotlin/org/usvm/dataflow/jvm/impl/NullabilityAssumptionAnalysisTest.kt
This PR transfers some dataflow analyses (namely, `NullAssumptionAnalysis` and `ReachingDefinitionsAnalysis`) from `jacodb-analysis` module (see https://github.com/UnitTestBot/jacodb/tree/5068453f689cfd789cad149c12c7fa03d36df353/jacodb-analysis/src/main/kotlin/org/jacodb/analysis/impl/custom), which is about to be completely removed from JacoDB (see https://github.com/UnitTestBot/jacodb/pull/280).
Note that tests for `ReachingDefinitionsAnalysis` were absent in the jacodb, so we they absent here as well. The tests for `NullAssumptionAnalysis` were dependent on some test infrastructure (`BaseTest` from `jacodb-core/testFixtures`), which was replaced by the existing `BaseAnalysisTest`.
> Add analyses from jacodb

- usvm-jvm-instrumentation/src/main/kotlin/org/usvm/instrumentation/executor/RdProcessRunner.kt
- usvm-jvm-instrumentation/src/main/kotlin/org/usvm/instrumentation/executor/TraceDeserializer.kt
- usvm-jvm-instrumentation/src/main/kotlin/org/usvm/instrumentation/instrumentation/JcInstructionTracer.kt
Needed to run instrumentation with empty folder as JRE
> Avoid calling JcClass.methods in instrumentation

- usvm-core/src/main/kotlin/org/usvm/Machine.kt
This PR adds the missing `State` bound in the recursive generic in `UMachine`.
This change allows for performing `State`-related operations on `state: State`. Most notably, `clone()` correctly returns the generic `State`, not just the base `UState<*>`.
> Add State bound for UMachine

- usvm-jvm-instrumentation/src/collectors/java/org/usvm/instrumentation/collector/trace/TraceCollector.java
When we use `LongHashSet` for storing traces, we obtain code coverage. So, we need the ability to get full original trace.
> Introduce `LongCollection` interface for storing instrumentation traces

- usvm-jvm-dataflow/src/test/kotlin/org/usvm/dataflow/jvm/impl/IfdsNpeTest.kt
- usvm-jvm-dataflow/src/test/kotlin/org/usvm/dataflow/jvm/impl/IfdsSqlTest.kt
- usvm-jvm-dataflow/src/test/kotlin/org/usvm/dataflow/jvm/impl/IfdsUnusedTest.kt
- usvm-jvm-dataflow/src/test/kotlin/org/usvm/dataflow/jvm/impl/JodaDateTimeAnalysisTest.kt
This PR disables some long jvm dataflow (IFDS) tests, enabling them only when env var `ENABLE_JVM_DATAFLOW_LONG_TESTS=true`.
> Disable long dataflow tests

- usvm-jvm-instrumentation/src/main/kotlin/org/usvm/instrumentation/testcase/descriptor/Descriptor2ValueConverter.kt
- usvm-jvm-instrumentation/src/main/kotlin/org/usvm/instrumentation/testcase/descriptor/Value2DescriptorConverter.kt
`enumValue.toString()` is not necessarily an invective function, so using it to build descriptors is unsafe. Furthermore, the name of the `enumValueName` property suggests that `enumValue.name` is stored in it, but unexpectedly `enumValue.toString()` is stored in `enumValueName`.
> Store `enumValue.name` in `enumValueName` (not `enumValue.toString()`)

- usvm-jvm-instrumentation/src/test/kotlin/org/usvm/instrumentation/executor/ConcreteExecutorTests.kt
Test from https://github.com/UnitTestBot/usvm/pull/173 no longer fails
> Enable `ConcreteExecutorTests.static interface method call test()`

- .github/workflows/ci.yml
This PR adds a separate step in all GHA jobs for uploading Gradle reports (mainly, test results/failures). This would simplify the debugging of tests failing on CI: test reports contain full logs of failing tests, including a complete error message and a stacktrace, all in html form.
Note that the step condition `!cancelled()` forces the uploading step to execute _even if_ the previous steps failed.
> Upload Gradle reports

- usvm-core/src/main/kotlin/org/usvm/solver/Solver.kt
- usvm-core/src/main/kotlin/org/usvm/utils/ResultUtils.kt
- usvm-core/src/test/kotlin/org/usvm/solver/SoftConstraintsTest.kt
- usvm-core/src/test/kotlin/org/usvm/types/TypeSolverTest.kt
- usvm-jvm/src/main/kotlin/org/usvm/machine/interpreter/JcInterpreter.kt
- usvm-ts/src/main/kotlin/org/usvm/machine/interpreter/TSInterpreter.kt
This PR adds `USolverResult<T>.ensureSat(): USatResult<T>` extension function to replace "unsafe" casts `as USatResult<*>` with "safe" `.ensureSat()` calls.
> Add ensureSat

- usvm-ts/src/main/kotlin/org/usvm/machine/expr/TSExprResolver.kt
- usvm-ts/src/main/kotlin/org/usvm/machine/interpreter/TSInterpreter.kt
- usvm-ts/src/main/kotlin/org/usvm/machine/operator/TSBinaryOperator.kt
- usvm-ts/src/main/kotlin/org/usvm/machine/state/TSMethodResult.kt
- usvm-ts/src/main/kotlin/org/usvm/machine/state/TSState.kt
- usvm-ts/src/main/kotlin/org/usvm/machine/state/TSStateUtils.kt
- usvm-ts/src/test/kotlin/org/usvm/samples/Call.kt
- usvm-ts/src/test/resources/samples/Call.ts
This PR adds support for simple call in TS.
> Support simple calls

- usvm-ts/src/test/kotlin/org/usvm/samples/Call.kt
- usvm-ts/src/test/resources/samples/Call.ts
This PR fixes missed handling of `NaN` in `Call.ts` test. Without this fix, `fib(NaN)` must have produced an infinite recursion, but the tests were too weak and skipped this error.
> Handle NaN in fib

- usvm-ts/src/main/kotlin/org/usvm/api/TsTest.kt
- usvm-ts/src/main/kotlin/org/usvm/machine/TsContext.kt
- usvm-ts/src/main/kotlin/org/usvm/machine/expr/TsExprResolver.kt
- usvm-ts/src/main/kotlin/org/usvm/machine/interpreter/TsInterpreter.kt
- usvm-ts/src/test/kotlin/org/usvm/samples/Arrays.kt
- usvm-ts/src/test/kotlin/org/usvm/samples/MinValue.kt
- usvm-ts/src/test/kotlin/org/usvm/util/TsMethodTestRunner.kt
- usvm-ts/src/test/kotlin/org/usvm/util/TsTestResolver.kt
- usvm-ts/src/test/resources/samples/Arrays.ts
Required TODO:  
* Reading by an index not from the indices range (e.g., -1, 123132, 1.4, etc)
* Change the length of the array (both writing in non-existing index and methods with shift/unshift)
* Make it possible to write values of different types into a created homogeneous array, e.g. boolean in the array of numbers
* Errors for incorrect array creation, e.g, negative length, object as a length, etc.
> Add support for arrays

- usvm-ts/src/main/kotlin/org/usvm/machine/expr/ExprUtil.kt
- usvm-ts/src/main/kotlin/org/usvm/machine/expr/TsExprResolver.kt
- usvm-ts/src/main/kotlin/org/usvm/machine/operator/TsUnaryOperator.kt
- usvm-ts/src/test/kotlin/org/usvm/samples/Numeric.kt
- usvm-ts/src/test/resources/samples/Numeric.ts
This PR adds `mkNumericExpr` to mimic [`ToNumber` method](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-tonumber) from ECMA spec.
It is yet unclear what to do with arbitrary objects, since the process of converting them to numbers relies on `toString`, which is then parsed to a number.
And currently this PR does not yet handle fake objects, but some simple cases (wrapped numbers/booleans) _could_ be handled.
> Add mkNumericExpr

- usvm-ts/src/test/kotlin/org/usvm/samples/And.kt
- usvm-ts/src/test/kotlin/org/usvm/samples/Arrays.kt
- usvm-ts/src/test/kotlin/org/usvm/samples/Call.kt
- usvm-ts/src/test/kotlin/org/usvm/samples/Equality.kt
- usvm-ts/src/test/kotlin/org/usvm/samples/InstanceFields.kt
- usvm-ts/src/test/kotlin/org/usvm/samples/InstanceMethods.kt
- usvm-ts/src/test/kotlin/org/usvm/samples/MinValue.kt
- usvm-ts/src/test/kotlin/org/usvm/samples/Neg.kt
- usvm-ts/src/test/kotlin/org/usvm/samples/Null.kt
- usvm-ts/src/test/kotlin/org/usvm/samples/Numeric.kt
- usvm-ts/src/test/kotlin/org/usvm/samples/Or.kt
- usvm-ts/src/test/kotlin/org/usvm/samples/StaticMethods.kt
- usvm-ts/src/test/kotlin/org/usvm/samples/Truthy.kt
- usvm-ts/src/test/kotlin/org/usvm/samples/TypeCoercion.kt
- usvm-ts/src/test/kotlin/org/usvm/samples/Undefined.kt
- usvm-ts/src/test/kotlin/org/usvm/util/TsMethodTestRunner.kt
This PR adds `loadSampleScene` for TS test runner.
> Extract common code for loading sample scene

- usvm-ts/src/main/kotlin/org/usvm/machine/expr/TsExprResolver.kt
- usvm-ts/src/main/kotlin/org/usvm/util/Utils.kt
- usvm-ts/src/test/kotlin/org/usvm/util/TsMethodTestRunner.kt
This PR adds simple (yet better than it was before) call/field resolver.
Also, we decided to turn off ArkAnalyzer's type inference in order to test and evaluate our SE engine more carefully in situation when most of the value have unknown types. Known types are beneficial, but currently we might unconsciously rely on their presence too much. Fixing the issues with call/field resolver in this PR allowed to pass the test suite we already have. If necessary, AA's type inference can be enable via an option during the scene loading.
> Add call/field resolver, disable AA type inference

- usvm-ts-dataflow/src/main/kotlin/org/usvm/dataflow/ts/graph/EtsApplicationGraph.kt
- usvm-ts-dataflow/src/main/kotlin/org/usvm/dataflow/ts/infer/AccessPath.kt
- usvm-ts-dataflow/src/main/kotlin/org/usvm/dataflow/ts/infer/Alias.kt
- usvm-ts-dataflow/src/main/kotlin/org/usvm/dataflow/ts/infer/ForwardAnalyzer.kt
- usvm-ts-dataflow/src/main/kotlin/org/usvm/dataflow/ts/infer/ForwardFlowFunctions.kt
- usvm-ts-dataflow/src/main/kotlin/org/usvm/dataflow/ts/infer/LiveVariables.kt
- usvm-ts-dataflow/src/main/kotlin/org/usvm/dataflow/ts/infer/TypeInferenceManager.kt
- usvm-ts-dataflow/src/main/kotlin/org/usvm/dataflow/ts/infer/cli/InferTypes.kt
- usvm-ts-dataflow/src/main/kotlin/org/usvm/dataflow/ts/util/EtsTraits.kt
- usvm-ts-dataflow/src/test/kotlin/org/usvm/dataflow/ts/test/EtsTypeResolverPerformanceTest.kt
- usvm-ts-dataflow/src/test/kotlin/org/usvm/dataflow/ts/test/utils/AbcProjects.kt
- usvm-ts-dataflow/src/test/kotlin/org/usvm/dataflow/ts/test/utils/PerformanceReport.kt
- Add liveness analysis before type inference
- `ForwardAnalyzer` stores facts about the variable immediately after the last instruction where the variable was used and `ForwardFlowFunction` drops facts about dead variables. This pre-analysis slightly increases the total performance without loss of precision.
- Fixed tests: now we doesn't take into account time spent to compute statistics
- Add flags for `ForwardAnalyzer` and `ForwardFlowFunctions` to enable/disable pre-analysis (alias and/or liveness)
- Add index to speed up callee resolver
> Add live variables analysis before type inference

- .github/workflows/ci.yml
- buildSrc/src/main/kotlin/Dependencies.kt
- usvm-ts/src/test/kotlin/org/usvm/samples/StaticFields.kt
This PR updates jacodb to the latest `neo` branch.
> Bump jacodb

- usvm-jvm/src/test/kotlin/org/usvm/samples/recursion/RecursionTest.kt
Fix coverage stop strategy for a recursion test to speed up tests
> Fix stop strategy for coverage

- .github/workflows/ci.yml
- buildSrc/src/main/kotlin/usvm.kotlin-conventions.gradle.kts
- usvm-ts/src/main/kotlin/org/usvm/api/checkers/UnreachableCodeDetector.kt
- usvm-ts/src/main/kotlin/org/usvm/machine/TsContext.kt
- usvm-ts/src/main/kotlin/org/usvm/machine/TsGraph.kt
- usvm-ts/src/main/kotlin/org/usvm/machine/TsMachine.kt
- usvm-ts/src/main/kotlin/org/usvm/machine/TsMethodCall.kt
- usvm-ts/src/main/kotlin/org/usvm/machine/expr/TsExprResolver.kt
- usvm-ts/src/main/kotlin/org/usvm/machine/interpreter/TsInterpreter.kt
- usvm-ts/src/main/kotlin/org/usvm/machine/interpreter/TsStatic.kt
- usvm-ts/src/main/kotlin/org/usvm/machine/operator/TsBinaryOperator.kt
- usvm-ts/src/main/kotlin/org/usvm/machine/state/TsState.kt
- usvm-ts/src/main/kotlin/org/usvm/machine/types/FakeType.kt
- usvm-ts/src/main/kotlin/org/usvm/util/LValueUtil.kt
- usvm-ts/src/main/kotlin/org/usvm/util/MethodResolver.kt
- usvm-ts/src/test/kotlin/org/usvm/samples/Call.kt
- usvm-ts/src/test/resources/samples/Call.ts
This PR adds support for virtual (via forking) and concrete calls in TS interpreter.
> Improve calls in TS machine

- usvm-ts/src/main/kotlin/org/usvm/api/TsTest.kt
- usvm-ts/src/main/kotlin/org/usvm/machine/TsContext.kt
- usvm-ts/src/main/kotlin/org/usvm/machine/expr/TsExprResolver.kt
- usvm-ts/src/main/kotlin/org/usvm/machine/interpreter/TsInterpreter.kt
- usvm-ts/src/main/kotlin/org/usvm/machine/types/TsTypeSystem.kt
- usvm-ts/src/test/kotlin/org/usvm/samples/InstanceFields.kt
- usvm-ts/src/test/kotlin/org/usvm/samples/Strings.kt
- usvm-ts/src/test/kotlin/org/usvm/samples/arrays/InputArrays.kt
- usvm-ts/src/test/kotlin/org/usvm/samples/types/ObjectUsage.kt
- usvm-ts/src/test/kotlin/org/usvm/util/Truthy.kt
- usvm-ts/src/test/kotlin/org/usvm/util/TsMethodTestRunner.kt
- usvm-ts/src/test/kotlin/org/usvm/util/TsTestResolver.kt
- usvm-ts/src/test/resources/samples/Strings.ts
- usvm-ts/src/test/resources/samples/arrays/InputArrays.ts
- usvm-ts/src/test/resources/samples/types/ObjectUsage.ts
- usvm-ts/src/test/resources/samples/types/StructuralEquality.ts
This PR adds support for strings in TS machine.
> Add support for Strings

- settings.gradle.kts
This PR enables [Gradle Build Scans](https://docs.gradle.org/current/userguide/build_scans.html).
- On CI (i.e. when `CI` env var is present), build scan publishing is turned on automatically (pass `--no-scan` to disable).
- Locally, build scans publishing is turned off. Pass `--scan` manually to publish a build scan.
> Enable Gradle Build Scans

- settings.gradle.kts
This PR fixes the automatic publishing of Gradle Build Scans in CI environment by correctly using `System.getenv` instead of `System.getProperty`.
Test locally with `CI=true gw compileKotlin`, this produces a build scan even without the `--scan` option.
> Fix publishing Build Scans on CI

- usvm-ts/src/test/kotlin/org/usvm/samples/operators/Division.kt
This PR disables soft constraints for the long running test `Division::testUnknownDivision`.
With default options, this test sometimes is very long. Without soft constraints, the test becomes fast.
> [TS] Fix long test Division::testUnknownDivision

- .github/workflows/ci.yml
- buildSrc/src/main/kotlin/Dependencies.kt
- buildSrc/src/main/kotlin/usvm.kotlin-conventions.gradle.kts
- settings.gradle.kts
- usvm-ts-dataflow/build.gradle.kts
- usvm-ts-dataflow/src/test/kotlin/org/usvm/dataflow/ts/test/EtsTypeInferenceTest.kt
- usvm-ts-dataflow/src/testFixtures/kotlin/org/usvm/dataflow/ts/TestFactoryDsl.kt
- usvm-ts/build.gradle.kts
- usvm-ts/src/test/kotlin/org/usvm/project/DemoCalc.kt
- usvm-ts/src/test/kotlin/org/usvm/project/DemoPhotos.kt
- usvm-ts/src/test/kotlin/org/usvm/project/ProjectRunner.kt
This PR provides a new implementation of TestFactory DSL for dynamic JUnit tests.
> [TS] Test factory DSL
